[color-theme]
name = "Solarized dark"

[color-theme.base]
white = "#93a1a1"
black = "#002b36"
grey = "#586e75"
blue = "#268bd2"
red = "#dc322f"
yellow = "#b58900"
orange = "#cb4b16"
green = "#859900"
purple = "#6c71c4"
cyan = "#2aa198"
magenta = "#d33682"

[color-theme.syntax]
attribute = "$yellow"
builtinType = "$cyan"
comment = "#5C6370"
constant = "$yellow"
constructor = "$yellow"
embedded = "$cyan"
enum = "$yellow"
enum-member = "$red"
enumMember = "$red"
escape = "$cyan"
field = "$magenta"
function = "$blue"
"function.method" = "$blue"
interface = "$purple"
keyword = "$green"
"keyword.control" = "$green"
method = "$blue"
number = "$blue"
property = "$blue"
"punctuation.delimiter" = "$blue"
selfKeyword = "$magenta"
string = "$cyan"
"string.escape" = "$red"
struct = "$yellow"
structure = "$cyan"
symbol = "$red"
tag = "$green"
"text.reference" = "$yellow"
"text.title" = "$blue"
"text.uri" = "$cyan"
type = "$yellow"
"type.builtin" = "$magenta"
typeAlias = "$orange"
variable = "$white"
"variable.other.member" = "$blue"


[color-theme.ui]
"activity.background" = "$red"
"activity.current" = "$white"
"completion.background" = "#073642"
"completion.current" = "$green"
"completion_lens.foreground" = "#93a1a1"
"editor.background" = "$black"
"editor.caret" = "$yellow"
"editor.current_line" = "#073642"
"editor.dim" = "#586e75"
"editor.drag_drop_background" = "#79c1fc55"
"editor.drag_drop_tab_background" = "#0b0e1455"
"editor.focus" = "$grey"
"editor.foreground" = "$white"
"editor.indent_guide" = "$grey"
"editor.link" = "$blue"
"editor.selection" = "#586e75"
"editor.sticky_header_background" = "$black"
"editor.visible_whitespace" = "$grey"
"error_lens.error.background" = "#E06C7520"
"error_lens.error.foreground" = "$red"
"error_lens.other.background" = "#5C637020"
"error_lens.other.foreground" = "$green"
"error_lens.warning.background" = "#E5C07B20"
"error_lens.warning.foreground" = "$yellow"
"hover.background" = "#00f"
"inlay_hint.background" = "#528bFF88"
"inlay_hint.foreground" = "$white"
"lapce.border" = "$grey"
"lapce.button.primary.background" = "#073642"
"lapce.button.primary.foreground" = "$white"
"lapce.dropdown_shadow" = "#000000"
"lapce.error" = "$red"
"lapce.icon.active" = "$white"
"lapce.icon.inactive" = "#5C6370"
"lapce.plugin.author" = "$purple"
"lapce.plugin.description" = "#839496"
"lapce.plugin.name" = "$white"
"lapce.remote.connected" = "$green"
"lapce.remote.connecting" = "$yellow"
"lapce.remote.disconnected" = "$red"
"lapce.remote.icon" = "$black"
"lapce.remote.local" = "$blue"
"lapce.scroll_bar" = "#657b83"
"lapce.tab.active.background" = "#073642"
"lapce.tab.active.foreground" = "$white"
"lapce.tab.active.underline" = "$yellow"
"lapce.tab.inactive.background" = "$black"
"lapce.tab.inactive.foreground" = "$grey"
"lapce.tab.inactive.underline" = "#528BFF77"
"lapce.tab.separator" = "$grey"
"lapce.warn" = "$yellow"
"markdown.blockquote" = "$blue"
"palette.background" = "$black"
"palette.current.background" = "#073642"
"palette.current.foreground" = "$white"
"palette.foreground" = "$white"
"panel.background" = "$black"
"panel.current.background" = "#073642"
"panel.current.foreground" = "$white"
"panel.current.foreground.dim" = "#f00"
"panel.foreground" = "$white"
"panel.foreground.dim" = "#657b83"
"panel.hovered.background" = "#073642"
"panel.hovered.foreground" = "$white"
"panel.hovered.foreground.dim" = "$blue"
"source_control.added" = "#50A14F32"
"source_control.modified" = "#0184BC32"
"source_control.removed" = "#FF526632"
"status.background" = "$black"
"status.foreground" = "$white"
"status.modal.insert.background" = "$blue"
"status.modal.insert.foreground" = "#black"
"status.modal.normal.background" = "$green"
"status.modal.normal.foreground" = "$black"
"status.modal.terminal.background" = "#56b6ff"
"status.modal.terminal.foreground" = "$black"
"status.modal.visual.background" = "$purple"
"status.modal.visual.foreground" = "$black"
"terminal.background" = "$black"
"terminal.black" = "#073642"
"terminal.blue" = "$blue"
"terminal.bright_black" = "#586e75"
"terminal.bright_blue" = "$blue"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_green" = "$green"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_red" = "$red"
"terminal.bright_white" = "$white"
"terminal.bright_yellow" = "$yellow"
"terminal.cursor" = "$yellow"
"terminal.cyan" = "$cyan"
"terminal.foreground" = "$white"
"terminal.green" = "$green"
"terminal.magenta" = "$magenta"
"terminal.red" = "$red"
"terminal.white" = "$white"
"terminal.yellow" = "$yellow"

[ui]
font-family = ""
font-size = 13
icon-size = 0
header-height = 35
status-height = 25
tab-min-width = 100
scroll-width = 10
drop-shadow-width = 0
preview-editor-width = 0
hover-font-family = ""
hover-font-size = 0
trim-search-results-whitespace = true
list-line-height = 25
